// English (data-only) counterpart of questions.ts.
// Screen-by-screen definitions consumed by the same rendering layer; scoring logic lives in engine.ts.
// Keep this file structurally in sync with questions.ts: same keys, same order, only the display strings are translated.

export type { Step, Option, StepKind } from './questions';

import type { Answers } from './types';
import type { Step } from './questions';

export const SECTIONS = [
  { key: 'profil', label: 'Your profile' },
  { key: 'budget', label: 'Income & budget' },
  { key: 'patrimoine', label: 'Assets' },
  { key: 'fiscalite', label: 'Tax & protection' },
  { key: 'objectifs', label: 'Objectives' },
] as const;

const estProprietaire = (a: Answers) =>
  a.logement === 'proprietaire' || a.logement === 'proprietaire_credit';

export const STEPS: Step[] = [
  {
    id: 'age',
    field: 'age',
    section: 'profil',
    kind: 'slider',
    eyebrow: 'Your profile',
    question: 'How old are you?',
    help: 'A wealth strategy should always be considered in light of your life horizon.',
    min: 18,
    max: 85,
    step: 1,
    suffix: ' years old',
    defaultValue: 40,
  },
  {
    id: 'situation',
    field: 'situation',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Your profile',
    question: 'What is your family situation?',
    options: [
      { value: 'celibataire', label: 'Single', icon: 'user' },
      { value: 'couple', label: 'In a relationship', icon: 'users' },
      { value: 'marie_pacse', label: 'Married or in a civil partnership (PACS)', icon: 'rings' },
      { value: 'divorce', label: 'Divorced', icon: 'split' },
      { value: 'veuf', label: 'Widowed', icon: 'user' },
    ],
  },
  {
    id: 'enfants',
    field: 'enfants',
    section: 'profil',
    kind: 'slider',
    eyebrow: 'Your profile',
    question: 'How many dependents do you have?',
    help: 'Children or dependent relatives attached to your tax household.',
    min: 0,
    max: 8,
    step: 1,
    suffix: '',
    defaultValue: 0,
  },
  {
    id: 'statut',
    field: 'statut',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Your profile',
    question: 'What is your professional status?',
    help: 'Status changes everything: social security coverage, retirement, contributions and optimization levers are not the same.',
    options: [
      { value: 'salarie', label: 'Employee', hint: 'General social security scheme', icon: 'briefcase' },
      { value: 'cadre', label: 'Manager (cadre)', hint: 'General scheme + AGIRC (executive pension scheme)', icon: 'briefcase' },
      { value: 'micro_entrepreneur', label: 'Micro-entrepreneur', hint: 'Simplified sole trader status, URSSAF (French social contributions agency)', icon: 'tools' },
      { value: 'independant_tns', label: 'Self-employed / TNS', hint: 'Sole proprietorship, self-employed regime', icon: 'tools' },
      { value: 'profession_liberale', label: 'Liberal profession', hint: 'BNC (non-commercial profits), dedicated pension fund', icon: 'scale' },
      { value: 'gerant_sarl', label: 'Majority manager of a SARL', hint: 'TNS', icon: 'building' },
      { value: 'president_sas', label: 'President of a SAS / SASU', hint: 'Treated as an employee for social security purposes', icon: 'building' },
      { value: 'dirigeant', label: 'Other company director', hint: 'Corporate officer', icon: 'building' },
      { value: 'sportif_pro', label: 'Professional athlete', hint: 'Short career, concentrated income', icon: 'medal' },
      { value: 'fonctionnaire', label: 'Civil servant', icon: 'landmark' },
      { value: 'retraite', label: 'Retired', icon: 'leaf' },
      { value: 'sans_activite', label: 'Not currently working', icon: 'user' },
    ],
  },
  {
    id: 'anciennete',
    field: 'anciennete',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Your profile',
    question: 'How long have you been in this activity?',
    help: 'Useful to gauge your CFE (French local business tax, Cotisation Foncière des Entreprises) status, exempt in year one and due afterwards, and the ramp-up of your contributions.',
    options: [
      { value: 'moins_1an', label: 'Less than a year', hint: 'First year, often exempt from CFE', icon: 'clock' },
      { value: '1_a_2ans', label: '1 to 2 years', hint: 'CFE starts to apply', icon: 'clock' },
      { value: 'plus_2ans', label: 'More than 2 years', hint: 'Established activity', icon: 'clock' },
    ],
    condition: (a) =>
      a.statut === 'micro_entrepreneur' ||
      a.statut === 'independant_tns' ||
      a.statut === 'profession_liberale' ||
      a.statut === 'gerant_sarl',
  },
  {
    id: 'revenuMensuel',
    field: 'revenuMensuel',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Income & budget',
    question: 'What is your household’s net monthly income?',
    help: 'Salaries, self-employment income and net rental income combined.',
    suffix: ' €',
    unit: 'net, per month',
    placeholder: '3,500',
    min: 0,
    max: 100000,
  },
  {
    id: 'chargesMensuelles',
    field: 'chargesMensuelles',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Income & budget',
    question: 'What do you estimate your monthly living expenses to be?',
    help: 'Rent, food, energy, taxes, subscriptions. Excluding loan repayments.',
    suffix: ' €',
    unit: 'per month, excluding loans',
    placeholder: '1,800',
    min: 0,
    max: 100000,
  },
  {
    id: 'epargneMensuelle',
    field: 'epargneMensuelle',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Income & budget',
    question: 'How much are you able to save each month?',
    help: 'The amount you actually set aside, on average.',
    suffix: ' €',
    unit: 'per month',
    placeholder: '400',
    min: 0,
    max: 50000,
  },
  {
    id: 'logement',
    field: 'logement',
    section: 'patrimoine',
    kind: 'single',
    eyebrow: 'Assets',
    question: 'Regarding your primary residence, you are...',
    options: [
      { value: 'locataire', label: 'Renting', icon: 'key' },
      { value: 'proprietaire_credit', label: 'Owner, with an ongoing mortgage', icon: 'home' },
      { value: 'proprietaire', label: 'Owner, mortgage-free', icon: 'home' },
      { value: 'heberge', label: 'Living with family or friends, rent-free', icon: 'user' },
    ],
  },
  {
    id: 'valeurRP',
    field: 'valeurRP',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'What is the estimated value of your primary residence?',
    suffix: ' €',
    unit: 'market value',
    placeholder: '350,000',
    min: 0,
    max: 20000000,
    condition: estProprietaire,
  },
  {
    id: 'immoLocatif',
    field: 'immoLocatif',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'Do you own rental property? What is its value?',
    help: 'Total value of rented properties (0 if you don’t have any).',
    suffix: ' €',
    unit: 'value of rented properties',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 20000000,
  },
  {
    id: 'epargneDispo',
    field: 'epargneDispo',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'How much available savings do you have set aside?',
    help: 'Savings accounts, current accounts, immediately accessible savings.',
    suffix: ' €',
    unit: 'precautionary savings',
    placeholder: '15,000',
    min: 0,
    max: 10000000,
  },
  {
    id: 'assuranceVie',
    field: 'assuranceVie',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'What is the total balance of your life insurance policies?',
    help: 'All policies combined (0 if you don’t hold any).',
    suffix: ' €',
    unit: 'total balance',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'per',
    field: 'per',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'Do you have dedicated retirement savings (PER)?',
    help: 'Balance of your PER (Plan d’Épargne Retraite, the French retirement savings plan), 0 if none.',
    suffix: ' €',
    unit: 'PER balance',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'autresPlacements',
    field: 'autresPlacements',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'Do you hold other investments (SCPI, French real estate investment trusts, structured products...)?',
    help: 'Excluding life insurance, PER and brokerage accounts.',
    suffix: ' €',
    unit: 'other holdings',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'bourse',
    field: 'bourse',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'Finally, do you hold any direct stock market investments?',
    help: 'PEA (French tax-advantaged equity savings plan), brokerage account, shares, cryptoassets. For the overall picture.',
    suffix: ' €',
    unit: 'market value',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'creditCRD',
    field: 'creditCRD',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'What is the outstanding balance on your loans?',
    help: 'Mortgage, consumer, business. The total (0 if none).',
    suffix: ' €',
    unit: 'outstanding balance',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 20000000,
  },
  {
    id: 'creditMensualite',
    field: 'creditMensualite',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Assets',
    question: 'What do your monthly loan repayments add up to?',
    suffix: ' €',
    unit: 'per month, all loans combined',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 100000,
    condition: (a) => (a.creditCRD ?? 0) > 0,
  },
  {
    id: 'tmi',
    field: 'tmi',
    section: 'fiscalite',
    kind: 'single',
    eyebrow: 'Tax & protection',
    question: 'What is your marginal tax bracket (TMI, Tranche Marginale d’Imposition)?',
    help: 'This is the rate that applies to the top slice of your income. An estimate is enough.',
    options: [
      { value: '0', label: '0%', hint: 'Not taxable' },
      { value: '11', label: '11%', hint: 'Moderate income' },
      { value: '30', label: '30%', hint: 'Most common case' },
      { value: '41', label: '41%', hint: 'Higher income' },
      { value: '45', label: '45%', hint: 'Top bracket' },
    ],
  },
  {
    id: 'prevoyance',
    field: 'prevoyance',
    section: 'fiscalite',
    kind: 'single',
    eyebrow: 'Tax & protection',
    question: 'Are you covered in the event of a hard blow (death, disability)?',
    help: 'Beyond the base cover from your employer or scheme.',
    options: [
      { value: 'oui', label: 'Yes, dedicated protection cover', icon: 'shield' },
      { value: 'partiel', label: 'Partially', icon: 'shield' },
      { value: 'non', label: 'No, nothing specific', icon: 'alert' },
      { value: 'ne_sais_pas', label: 'I don’t know', icon: 'help' },
    ],
  },
  {
    id: 'objectifs',
    field: 'objectifs',
    section: 'objectifs',
    kind: 'multi',
    eyebrow: 'Your objectives',
    question: 'What matters most to you today?',
    help: 'Choose up to three priorities.',
    options: [
      { value: 'retraite', label: 'Prepare for retirement', icon: 'leaf' },
      { value: 'reduire_impots', label: 'Reduce my taxes', icon: 'coins' },
      { value: 'investir_immobilier', label: 'Invest in real estate', icon: 'home' },
      { value: 'faire_fructifier', label: 'Grow my savings', icon: 'trending' },
      { value: 'proteger_famille', label: 'Protect my family', icon: 'shield' },
      { value: 'transmettre', label: 'Pass on my wealth', icon: 'gift' },
      { value: 'residence_principale', label: 'Buy my primary residence', icon: 'home' },
      { value: 'constituer_epargne', label: 'Build up savings', icon: 'piggy' },
      { value: 'revenus_complementaires', label: 'Generate additional income', icon: 'coins' },
    ],
  },
  {
    id: 'horizon',
    field: 'horizon',
    section: 'objectifs',
    kind: 'single',
    eyebrow: 'Your objectives',
    question: 'What is your investment horizon?',
    options: [
      { value: 'court', label: 'Less than 3 years', hint: 'Short term', icon: 'clock' },
      { value: 'moyen', label: '3 to 8 years', hint: 'Medium term', icon: 'clock' },
      { value: 'long', label: '8 to 15 years', hint: 'Long term', icon: 'clock' },
      { value: 'tres_long', label: 'More than 15 years', hint: 'Very long term', icon: 'clock' },
    ],
  },
  {
    id: 'risque',
    field: 'risque',
    section: 'objectifs',
    kind: 'single',
    eyebrow: 'Your objectives',
    question: 'How would you describe yourself when it comes to risk?',
    help: 'There is no right answer: this guides the strategy, not your worth.',
    options: [
      { value: 'securite', label: 'Security above all', hint: 'I want to preserve my capital', icon: 'shield' },
      { value: 'prudent', label: 'Fairly cautious', hint: 'A little risk, measured', icon: 'shield' },
      { value: 'equilibre', label: 'Balanced', hint: 'A fair balance between return and risk', icon: 'scale' },
      { value: 'dynamique', label: 'Dynamic', hint: 'I aim for long-term performance', icon: 'trending' },
    ],
  },
];
