// Définition data-driven du parcours : une entrée = un écran (une seule question).
// Le rendu (Astro/JS) consomme ce schéma ; la logique de score vit dans engine.ts.
// Ajouter, retirer ou réordonner un écran ne demande que d'éditer ce fichier.

import type { Answers } from './types';

export type StepKind = 'single' | 'multi' | 'number' | 'slider';

export interface Option {
  value: string;
  label: string;
  hint?: string;
  icon?: string; // clé d'icône résolue en SVG inline côté page
}

export interface Step {
  id: string;
  field: keyof Answers;
  section: string;
  kind: StepKind;
  question: string;
  help?: string;
  eyebrow?: string;
  options?: Option[];
  min?: number;
  max?: number;
  step?: number;
  suffix?: string;
  unit?: string; // libellé affiché sous le nombre (ex. "par mois")
  placeholder?: string;
  optional?: boolean;
  defaultValue?: number | string;
  // Écran affiché seulement si la condition est vraie (sinon sauté).
  condition?: (a: Answers) => boolean;
}

export const SECTIONS = [
  { key: 'profil', label: 'Votre profil' },
  { key: 'budget', label: 'Revenus & budget' },
  { key: 'patrimoine', label: 'Patrimoine' },
  { key: 'fiscalite', label: 'Fiscalité & protection' },
  { key: 'objectifs', label: 'Objectifs' },
] as const;

const estProprietaire = (a: Answers) =>
  a.logement === 'proprietaire' || a.logement === 'proprietaire_credit';

export const STEPS: Step[] = [
  {
    id: 'age',
    field: 'age',
    section: 'profil',
    kind: 'slider',
    eyebrow: 'Votre profil',
    question: 'Quel âge avez-vous ?',
    help: 'La stratégie patrimoniale se lit toujours au regard de votre horizon de vie.',
    min: 18,
    max: 85,
    step: 1,
    suffix: ' ans',
    defaultValue: 40,
  },
  {
    id: 'situation',
    field: 'situation',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Votre profil',
    question: 'Quelle est votre situation familiale ?',
    options: [
      { value: 'celibataire', label: 'Célibataire', icon: 'user' },
      { value: 'couple', label: 'En couple', icon: 'users' },
      { value: 'marie_pacse', label: 'Marié(e) ou pacsé(e)', icon: 'rings' },
      { value: 'divorce', label: 'Divorcé(e)', icon: 'split' },
      { value: 'veuf', label: 'Veuf / veuve', icon: 'user' },
    ],
  },
  {
    id: 'enfants',
    field: 'enfants',
    section: 'profil',
    kind: 'slider',
    eyebrow: 'Votre profil',
    question: 'Combien de personnes sont à votre charge ?',
    help: 'Enfants ou proches rattachés à votre foyer fiscal.',
    min: 0,
    max: 8,
    step: 1,
    suffix: '',
    defaultValue: 0,
  },
  {
    id: 'statut',
    field: 'statut',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Votre profil',
    question: 'Quel est votre statut professionnel ?',
    help: 'Le statut change tout : couverture sociale, retraite, cotisations et leviers d’optimisation ne sont pas les mêmes.',
    options: [
      { value: 'salarie', label: 'Salarié(e)', hint: 'Régime général', icon: 'briefcase' },
      { value: 'cadre', label: 'Cadre', hint: 'Régime général + AGIRC', icon: 'briefcase' },
      { value: 'micro_entrepreneur', label: 'Micro-entrepreneur', hint: 'Auto-entreprise, URSSAF', icon: 'tools' },
      { value: 'independant_tns', label: 'Indépendant / TNS', hint: 'EI, régime des indépendants', icon: 'tools' },
      { value: 'profession_liberale', label: 'Profession libérale', hint: 'BNC, caisse dédiée', icon: 'scale' },
      { value: 'gerant_sarl', label: 'Gérant majoritaire de SARL', hint: 'TNS', icon: 'building' },
      { value: 'president_sas', label: 'Président de SAS / SASU', hint: 'Assimilé salarié', icon: 'building' },
      { value: 'dirigeant', label: 'Autre dirigeant', hint: 'Mandataire social', icon: 'building' },
      { value: 'sportif_pro', label: 'Sportif professionnel', hint: 'Carrière courte, revenus concentrés', icon: 'medal' },
      { value: 'fonctionnaire', label: 'Fonctionnaire', icon: 'landmark' },
      { value: 'retraite', label: 'Retraité(e)', icon: 'leaf' },
      { value: 'sans_activite', label: 'Sans activité', icon: 'user' },
    ],
  },
  {
    id: 'anciennete',
    field: 'anciennete',
    section: 'profil',
    kind: 'single',
    eyebrow: 'Votre profil',
    question: 'Depuis combien de temps exercez-vous cette activité ?',
    help: 'Utile pour situer la CFE (exonérée la 1re année, due ensuite) et la montée en charge de vos cotisations.',
    options: [
      { value: 'moins_1an', label: 'Moins d’un an', hint: '1re année, souvent exonérée de CFE', icon: 'clock' },
      { value: '1_a_2ans', label: '1 à 2 ans', hint: 'La CFE commence à s’appliquer', icon: 'clock' },
      { value: 'plus_2ans', label: 'Plus de 2 ans', hint: 'Activité installée', icon: 'clock' },
    ],
    condition: (a) =>
      a.statut === 'micro_entrepreneur' ||
      a.statut === 'independant_tns' ||
      a.statut === 'profession_liberale' ||
      a.statut === 'gerant_sarl',
  },
  {
    id: 'revenuMensuel',
    field: 'revenuMensuel',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Revenus & budget',
    question: 'Quels sont les revenus nets du foyer, par mois ?',
    help: 'Salaires, revenus d’activité et revenus locatifs nets confondus.',
    suffix: ' €',
    unit: 'net, par mois',
    placeholder: '3 500',
    min: 0,
    max: 100000,
  },
  {
    id: 'chargesMensuelles',
    field: 'chargesMensuelles',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Revenus & budget',
    question: 'À combien estimez-vous vos charges courantes mensuelles ?',
    help: 'Loyer, alimentation, énergie, impôts, abonnements. Hors mensualités de crédit.',
    suffix: ' €',
    unit: 'par mois, hors crédits',
    placeholder: '1 800',
    min: 0,
    max: 100000,
  },
  {
    id: 'epargneMensuelle',
    field: 'epargneMensuelle',
    section: 'budget',
    kind: 'number',
    eyebrow: 'Revenus & budget',
    question: 'Combien parvenez-vous à épargner chaque mois ?',
    help: 'Le montant que vous mettez réellement de côté, en moyenne.',
    suffix: ' €',
    unit: 'par mois',
    placeholder: '400',
    min: 0,
    max: 50000,
  },
  {
    id: 'logement',
    field: 'logement',
    section: 'patrimoine',
    kind: 'single',
    eyebrow: 'Patrimoine',
    question: 'Concernant votre résidence principale, vous êtes...',
    options: [
      { value: 'locataire', label: 'Locataire', icon: 'key' },
      { value: 'proprietaire_credit', label: 'Propriétaire, avec crédit en cours', icon: 'home' },
      { value: 'proprietaire', label: 'Propriétaire, sans crédit', icon: 'home' },
      { value: 'heberge', label: 'Hébergé(e) à titre gratuit', icon: 'user' },
    ],
  },
  {
    id: 'valeurRP',
    field: 'valeurRP',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Quelle est la valeur estimée de votre résidence principale ?',
    suffix: ' €',
    unit: 'valeur de marché',
    placeholder: '350 000',
    min: 0,
    max: 20000000,
    condition: estProprietaire,
  },
  {
    id: 'immoLocatif',
    field: 'immoLocatif',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Détenez-vous de l’immobilier locatif ? Quelle valeur ?',
    help: 'Valeur totale des biens loués (0 si vous n’en avez pas).',
    suffix: ' €',
    unit: 'valeur des biens loués',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 20000000,
  },
  {
    id: 'epargneDispo',
    field: 'epargneDispo',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Quelle épargne disponible avez-vous de côté ?',
    help: 'Livrets, comptes courants, épargne immédiatement mobilisable.',
    suffix: ' €',
    unit: 'épargne de précaution',
    placeholder: '15 000',
    min: 0,
    max: 10000000,
  },
  {
    id: 'assuranceVie',
    field: 'assuranceVie',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Quel est l’encours de vos assurances-vie ?',
    help: 'Tous contrats confondus (0 si vous n’en détenez pas).',
    suffix: ' €',
    unit: 'encours total',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'per',
    field: 'per',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Avez-vous une épargne retraite dédiée (PER) ?',
    help: 'Encours de votre Plan d’Épargne Retraite (0 si aucun).',
    suffix: ' €',
    unit: 'encours PER',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'autresPlacements',
    field: 'autresPlacements',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Détenez-vous d’autres placements (SCPI, produits structurés...) ?',
    help: 'Hors assurance-vie, PER et comptes-titres.',
    suffix: ' €',
    unit: 'autres supports',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'bourse',
    field: 'bourse',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Enfin, avez-vous des placements boursiers en direct ?',
    help: 'PEA, compte-titres, actions, cryptoactifs. Pour la photographie d’ensemble.',
    suffix: ' €',
    unit: 'valeur de marché',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 10000000,
  },
  {
    id: 'creditCRD',
    field: 'creditCRD',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'Quel est le capital restant dû de vos crédits ?',
    help: 'Immobilier, consommation, professionnel. Le total (0 si aucun).',
    suffix: ' €',
    unit: 'capital restant dû',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 20000000,
  },
  {
    id: 'creditMensualite',
    field: 'creditMensualite',
    section: 'patrimoine',
    kind: 'number',
    eyebrow: 'Patrimoine',
    question: 'À combien s’élèvent vos mensualités de crédit ?',
    suffix: ' €',
    unit: 'par mois, tous crédits',
    placeholder: '0',
    optional: true,
    defaultValue: 0,
    min: 0,
    max: 100000,
    condition: (a) => (a.creditCRD ?? 0) > 0,
  },
  {
    id: 'tmi',
    field: 'tmi',
    section: 'fiscalite',
    kind: 'single',
    eyebrow: 'Fiscalité & protection',
    question: 'Quelle est votre tranche marginale d’imposition ?',
    help: 'C’est le taux qui s’applique à la dernière tranche de vos revenus. Une estimation suffit.',
    options: [
      { value: '0', label: '0 %', hint: 'Non imposable' },
      { value: '11', label: '11 %', hint: 'Revenus modérés' },
      { value: '30', label: '30 %', hint: 'Cas le plus fréquent' },
      { value: '41', label: '41 %', hint: 'Revenus élevés' },
      { value: '45', label: '45 %', hint: 'Tranche supérieure' },
    ],
  },
  {
    id: 'prevoyance',
    field: 'prevoyance',
    section: 'fiscalite',
    kind: 'single',
    eyebrow: 'Fiscalité & protection',
    question: 'Êtes-vous couvert(e) en cas de coup dur (décès, invalidité) ?',
    help: 'Au-delà de la couverture de base de votre employeur ou régime.',
    options: [
      { value: 'oui', label: 'Oui, une prévoyance dédiée', icon: 'shield' },
      { value: 'partiel', label: 'Partiellement', icon: 'shield' },
      { value: 'non', label: 'Non, rien de spécifique', icon: 'alert' },
      { value: 'ne_sais_pas', label: 'Je ne sais pas', icon: 'help' },
    ],
  },
  {
    id: 'objectifs',
    field: 'objectifs',
    section: 'objectifs',
    kind: 'multi',
    eyebrow: 'Vos objectifs',
    question: 'Qu’est-ce qui compte le plus pour vous aujourd’hui ?',
    help: 'Choisissez jusqu’à trois priorités.',
    options: [
      { value: 'retraite', label: 'Préparer ma retraite', icon: 'leaf' },
      { value: 'reduire_impots', label: 'Réduire mes impôts', icon: 'coins' },
      { value: 'investir_immobilier', label: 'Investir dans l’immobilier', icon: 'home' },
      { value: 'faire_fructifier', label: 'Faire fructifier mon épargne', icon: 'trending' },
      { value: 'proteger_famille', label: 'Protéger ma famille', icon: 'shield' },
      { value: 'transmettre', label: 'Transmettre mon patrimoine', icon: 'gift' },
      { value: 'residence_principale', label: 'Acheter ma résidence principale', icon: 'home' },
      { value: 'constituer_epargne', label: 'Me constituer une épargne', icon: 'piggy' },
      { value: 'revenus_complementaires', label: 'Générer des revenus complémentaires', icon: 'coins' },
    ],
  },
  {
    id: 'horizon',
    field: 'horizon',
    section: 'objectifs',
    kind: 'single',
    eyebrow: 'Vos objectifs',
    question: 'Sur quel horizon souhaitez-vous investir ?',
    options: [
      { value: 'court', label: 'Moins de 3 ans', hint: 'Court terme', icon: 'clock' },
      { value: 'moyen', label: '3 à 8 ans', hint: 'Moyen terme', icon: 'clock' },
      { value: 'long', label: '8 à 15 ans', hint: 'Long terme', icon: 'clock' },
      { value: 'tres_long', label: 'Plus de 15 ans', hint: 'Très long terme', icon: 'clock' },
    ],
  },
  {
    id: 'risque',
    field: 'risque',
    section: 'objectifs',
    kind: 'single',
    eyebrow: 'Vos objectifs',
    question: 'Face au risque, comment vous décririez-vous ?',
    help: 'Il n’y a pas de bonne réponse : cela oriente la stratégie, pas votre valeur.',
    options: [
      { value: 'securite', label: 'Sécurité avant tout', hint: 'Je veux préserver mon capital', icon: 'shield' },
      { value: 'prudent', label: 'Plutôt prudent(e)', hint: 'Un peu de risque, mesuré', icon: 'shield' },
      { value: 'equilibre', label: 'Équilibré(e)', hint: 'Un juste milieu rendement / risque', icon: 'scale' },
      { value: 'dynamique', label: 'Dynamique', hint: 'Je vise la performance long terme', icon: 'trending' },
    ],
  },
];
